# tests/test_imports.py
def test_imports():
    import jcb_api.main
    import jcb_bond_project.cashflow_model.builders
    import jcb_bond_project.cashflow_model.conv_bond_model
    import jcb_bond_project.portfolio.portfolio_builders
    import jcb_bond_project.portfolio.portfolio_optimiser
    import jcb_bond_project.database.db
    import jcb_bond_project.database.insert
    import jcb_bond_project.database.query
    import jcb_bond_project.models.instrument
    import jcb_bond_project.models.instrument_data
    import jcb_bond_project.utils.jcb_calendar
    import jcb_bond_project.utils.identifiers